# .gitlab-ci.yml

stages:
  - a
  - b
  - build
  - test
  - deploy

a:
  stage: a
  script: sleep 40


b:
  stage: b
  script: sleep 40
  needs:
    - a

linux build:
  stage: build
  script: sleep 10 && echo Done

mac build:
  stage: build
  script: sleep 20 && echo Done

lint:
  stage: test
  needs: []
  script: echo Done

linux unit tests:
  stage: test
  needs:
    - linux build
  script: echo Done

linux e2e tests:
  stage: test
  needs:
    - linux build
  script: sleep 10 && echo Done

mac unit tests:
  stage: test
  needs:
    - mac build
  script: sleep 5 && echo Done

mac e2e tests:
  stage: test
  needs:
    - mac build
  script: sleep 30 && echo Done

release linux:
  stage: deploy
  script: "echo Done"
  needs:
    - linux unit tests
    - linux e2e tests
    - a
    - b

release mac:
  stage: deploy
  script: "echo Done"
  needs:
    - mac unit tests
    - b
    - mac e2e tests
