stages:
  - build
  - test
  - deploy

build:
  stage: build
  script: echo Build
  except:
    variables:
      - $SKIP_STAGE_build == "1"

test:
  stage: test
  script: echo Test ...
  except:
    variables:
      - $SKIP_STAGE_test == "1"

deploy:
  stage: deploy
  script: echo Deploy
  except:
    variables:
      - $SKIP_STAGE_deploy == "1"
