stages:
  - a
  - b
  - c
  - d

a:
  stage: a
  script: echo a
  when: manual

b:
  stage: b
  script: echo b
  when: manual
  
c:
  stage: c
  script: echo c
  when: manual
  
d:
  stage: d
  script: echo d
  